### ISSUE TITLE
 Rom compiling mdnsresponder error

### ISSUE THREAD

**Issue by rohit12043-zz** [PixysOS/manifest#2]
while i was compiling my rom i got error 

[1/1] /home/rohit/pixy/out/soong/.minibootstrap...ome/rohit/pixy/out/soong/.bootstrap/build.ninj
[55/56] glob prebuilts/ndk/stl.bp
[78/78] /home/rohit/pixy/out/soong/.bootstrap/b...ng_build /home/rohit/pixy/out/soong/build.ninj
FAILED: /home/rohit/pixy/out/soong/build.ninja
/home/rohit/pixy/out/soong/.bootstrap/bin/soong_build -t -l /home/rohit/pixy/out/.module_paths/Android.bp.list -b /home/rohit/pixy/out/soong -n /home/rohit/pixy/out -d /home/rohit/pixy/out/soong/build.ninja.d -o /home/rohit/pixy/out/soong/build.ninja Android.bp
error: external/mdnsresponder/Android.bp:6:1: module "mdnsresponder_default_cflags" already defined
       mdnsresponder/Android.bp:6:1 <-- previous definition here
error: external/mdnsresponder/Android.bp:73:1: module "mdnsd" already defined
       mdnsresponder/Android.bp:73:1 <-- previous definition here
error: mdnsresponder/Android.bp:163:23: unrecognized property "recovery_available"
error: mdnsresponder/Android.bp:201:1: module "dnssd" already defined
       external/mdnsresponder/Android.bp:200:1 <-- previous definition here
ninja: build stopped: subcommand failed.
21:37:10 soong bootstrap failed with: exit status 1

#### failed to build some targets (54 seconds) ####

How to solve it?

**Comment by yash-garg** [comment]
@rohit12043 FFS Stop spamming it here
