### ISSUE TITLE
why repo syns faied

### ISSUE THREAD

**Issue by ghost** [PixysOS/manifest#8]
https://del.dog/gametocope

**Comment by Subinsmani** [comment]
@java67 Please re sync again. I think something issue from google server.

**Comment by ghost** [comment]
error: vendor/qcom/opensource/commonsys/bluetooth_ext/system_bt_ext/btconfigstore/Android.bp:11:1: dependency "vendor.qti.hardware.btconfigstore@2.0" of "libbtconfigstore" missing variant:
